Week17
Lidemy/mentor-program-5th-Wangpoching pull request #18
Opened 2021-09-12 20:28 UTC by Wangpoching

## 部落格

* [登入頁面](https://blog.bocyun.tw/login)
* [註冊頁面](https://blog.bocyun.tw/register)
因為是可以供大家申請的部落格網站，所以沒有設計共同的首頁
所以只好提供一個 demo
* 帳號: admin (p.s. 這個 admin 就只是一般的使用者，並沒有設計管理員的功能）
* 密碼: admin
* [admin 的部落格主頁](https://blog.bocyun.tw/blog/4q6rxvk7)

## 餐廳抽獎

* [後台登入頁面](https://getprize.bocyun.tw/login)
* [抽獎頁面](https://getprize.bocyun.tw/prize)

後台管理員登入資訊：
帳號: admin
密碼: admin

謝謝助教

2021-09-17 16:36 UTC, Wangpoching commented
0918 更新

目前餐廳網站因為在做 18 週作業正在重構，所以如果助教遇到抽獎功能不能用，可以請先幫我批改部落格的作業就好，餐廳網站 18 週再一併批改。

謝謝助教

2021-09-21 16:20 UTC, cwc329 requested changes

2021-09-21 16:20 UTC, cwc329 commented on homeworks/week17/hw1/config/config.json
> +{
這種機密敏感資料不要進版控。
請把這個移除版控並且刪除版控紀錄，
可以參考[這篇](https://mtr04-note.coderbridge.io/2020/08/09/about-git-deletefile/)。

2021-09-21 16:20 UTC, cwc329 commented
請先把 config.json 移除版控，
你也可以注意 week18 有沒有一樣的問題。

2021-10-15 18:59 UTC, closed without merging